# Generated by Django 2.1.7 on 2019-03-29 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dance_type', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_private', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='JoinTeacherStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('regular_class_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('private_class_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('join_date', models.DateField()),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.School')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('hourly_wage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.School')),
            ],
        ),
        migrations.AddField(
            model_name='danceclass',
            name='primary_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Teacher'),
        ),
        migrations.AddField(
            model_name='danceclass',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.School'),
        ),
    ]
