# Generated by Django 2.1.3 on 2019-04-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danceclass',
            old_name='primary_teacher',
            new_name='teacher_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='parent_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='student_first_name',
        ),
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
