# Generated by Django 2.1.3 on 2019-04-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_auto_20190402_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(),
        ),
    ]
