# Generated by Django 2.1.3 on 2019-04-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_auto_20190402_0307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoinTeacherStudent',
            new_name='JoinClassesAndStudents',
        ),
    ]
