# Generated by Django 2.1.3 on 2019-04-02 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_auto_20190402_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinclassesandstudents',
            name='class_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='studio.DanceClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joinclassesandstudents',
            name='student_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='studio.Student'),
            preserve_default=False,
        ),
    ]
